import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { configuration, laravel, packages } from '~/manifest.json'

// The command JSON files are regenerated by the process-artisan-commands
// workflow, so these tests guard the contract the app relies on: every version
// in the manifest has a well-formed asset file, and every command can produce
// a valid route slug.

const commandsByVersion = Object.fromEntries(
  laravel.map((version) => [
    version,
    JSON.parse(readFileSync(new URL(`../../assets/${version}.json`, import.meta.url), 'utf-8')),
  ]),
)

describe('manifest.json', () => {
  it('lists at least one Laravel version', () => {
    expect(laravel.length).toBeGreaterThan(0)
  })

  it('uses the N.x version format, newest first', () => {
    for (const version of laravel) {
      expect(version).toMatch(/^\d+\.x$/)
    }
    const majors = laravel.map((v) => parseInt(v, 10))
    expect(majors).toEqual([...majors].sort((a, b) => b - a))
  })

  it('lists packages as vendor/name with no version suffix', () => {
    expect(packages.length).toBeGreaterThan(0)
    for (const pkg of packages) {
      expect(pkg).toMatch(/^[\w.-]+\/[\w.-]+$/)
    }
  })

  it('has a package configuration for every version', () => {
    expect(Object.keys(configuration).sort()).toEqual([...laravel].sort())
  })

  it('only references known packages in version configurations', () => {
    const known = new Set(packages)
    for (const [version, pkgs] of Object.entries(configuration)) {
      for (const pkg of pkgs) {
        expect(known.has(pkg.split(':')[0]), `${version} references ${pkg}`).toBe(true)
      }
    }
  })
})

describe.each(laravel)('assets/%s.json', (version) => {
  const commands = commandsByVersion[version]

  it('contains a non-empty command list', () => {
    expect(Array.isArray(commands)).toBe(true)
    expect(commands.length).toBeGreaterThan(0)
  })

  it('has the fields the app renders on every command', () => {
    for (const command of commands) {
      expect(command.name, JSON.stringify(command)).toBeTypeOf('string')
      expect(command.name).not.toBe('')
      expect(command.description).toBeTypeOf('string')
      expect(command.synopsis).toBeTypeOf('string')
      expect(Array.isArray(command.aliases)).toBe(true)
      expect(Array.isArray(command.arguments)).toBe(true)
      expect(Array.isArray(command.options)).toBe(true)
    }
  })

  it('has unique command names', () => {
    const names = commands.map((c) => c.name)
    expect(new Set(names).size).toBe(names.length)
  })

  it('produces unique URL-safe route slugs', () => {
    // Pages and prerender routes slugify with a single replace(':', ''), so a
    // name may contain at most one colon and nothing else that breaks a URL.
    const slugs = commands.map((c) => c.name.replace(':', ''))
    expect(new Set(slugs).size).toBe(slugs.length)
    for (const slug of slugs) {
      expect(slug).toMatch(/^[\w.-]+$/)
    }
  })

  it('has well-formed arguments and options', () => {
    for (const command of commands) {
      for (const arg of command.arguments) {
        expect(arg.name, `${command.name} argument`).toBeTypeOf('string')
      }
      for (const opt of command.options) {
        expect(opt.name, `${command.name} option`).toBeTypeOf('string')
      }
    }
  })
})
